### ISSUE TITLE
Great work! Can you share the pretrained weights?

### ISSUE THREAD

**Issue by chenxian9999** [ebouteillon/kaggle-quickdraw-doodle-recognition-challenge#1]
Great work! Can you share the pretrained weights?

**Comment by ebouteillon** [comment]
Hi chenxian999,

Thanks for the nice words. :smile:

Unfortunately I kept the generated weights of my custom neural-network only for the duration of this Kaggle competition.
With the ipython notebook provided in this repository, it will take you about one day to generate them with a Nvidia rtx2080ti. If you don't have such a high end Nvidia GPU, simply reduce the batch size to fit the memory size of your GPU and wait a bit longer.
